### ISSUE TITLE
(Discussing?) Browser support

### ISSUE THREAD

**Issue by C0Nd3Mnd** [codazoda/neatcss#22]
# Introduction

So I was thinking about what would improve (opinionated) Neat CSS and I figured I'd add variables for the colors so they can be customized more easily. Right now you'd have to override quite a few properties in your `custom.css` to change the color(s) to your liking, with variables you'd just have to do something like this:

```css
:root {
    --light: #eee;
    --dark: #00a;
}
```

I checked browser compatibility with this feature on [caniuse.com](https://caniuse.com/css-variables) and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) and found out that it's compatible with pretty much any modern browser (and it has been supported in most browsers for quite a while).

# Issue

There are other CSS features that are more bleeding edge than this one though, so we should probably discuss (or just let the author @codazoda set it in stone) which browsers (and versions) Neat CSS has to support so deciding which features to use and which browsers to test becomes more streamlined.

My personal opinion:

- Current stable version and previous stable version of Chromium-based browsers (Microsoft Edge, Google Chrome, Chromium, Vivaldi; basically all browsers that are regularly updated to be on the current stable Chromium version)
- Current stable version and previous stable version of Firefox
- Current version of iOS (whatever browser, since all use the iOS Safari WebKit engine) + maybe the previous major version for a while after a new major version is released
- Current version of Safari for macOS
- Screw IE

The supported browsers (whatever they may be) should be noted in the README, website and/or contribution guidelines.

**Comment by codazoda** [comment]
![Screenshot_20210225-080431](https://user-images.githubusercontent.com/527246/109157785-83561080-7740-11eb-837a-6c0e8b62697b.png)

Quick screenshot, on my phone, of versions that support bar() in CSS.

I'm on vacation at the moment, but I need to spend some time researching this and make a decision on browsers. I'll probably base that decision on some report of browser use and set some cutoff for percentage.

Maybe something like this.

https://gs.statcounter.com/browser-version-market-share/desktop/worldwide/#monthly-202001-202101-bar

**Comment by codazoda** [comment]
This was merged but I didn't close the issue. Closing it now. :P
