### ISSUE TITLE
by default flexbox has flex direction to row

### ISSUE THREAD

**Issue by bzaman** [codazoda/neatcss#36]
## Issue description
neat.css on line number 101 `flex-direction: row;` is declared. When any element  declared with `display: flex`, by default it main axis behave like `row`.  `flex-direction: row` can be removed and it should performs and work as before. 

I would like to do a little PR.

**Comment by codazoda** [comment]
I’d be happy to review a PR for this

**Comment by bzaman** [comment]
Thank you. I will do a PR very soon
