### ISSUE TITLE
404 error problem

### ISSUE THREAD

**Issue by mroberts1** [codazoda/neatcss#44]
I'm confused. I followed the instructions exactly: downloaded the html and css files with curl, then renamed the neat.html to index.html. However, when I opened up index.html in my code editor (Brackets) and launched a local server to open it, I just got 404 error message. To make things more confusing, I see that the 404 message is contained in the index.html file itself - so neat.html is a 404 file? 

I don't understand why I'm getting a 404 message - should I not be running the file in a server? Do I need to delete the 404 part and add in new content of my own? Sorry but the instructions are very unclear.

**Comment by codazoda** [comment]
Uhg! You're right, I accidentally removed this file around the v1.0.0 release when I changed the release process. Thanks, so much, for pointing out the problem. I've corrected this in the following commit and this update is now live.

https://github.com/codazoda/neatcss/commit/96a135aeefd7d590f8668fd8ac52a72c02058e13
